# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.2
neo_version=26.2.0.59
mod_group=com.mrbysco.cobblegenhaters
mod_id=cobblegenhaters
mod_archive_name=Cobble-Gen-Haters

#Publishing
mod_name=Cobble Gen Haters
curseforge_id=305797
modrinth_id=fb5Ob6vt

# Version
version=3.0.0

# Dependencies
jei_minecraft=26.2
jei_version=30.16.0.129