# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.10
neo_version=21.10.49-beta
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
mod_group=com.mrbysco.cobblegenhaters
mod_id=cobblegenhaters
mod_archive_name=Cobble-Gen-Haters

#Publishing
mod_name=Cobble Gen Haters
curseforge_id=305797
modrinth_id=fb5Ob6vt

# Version
version=2.4.0

# Dependencies
jei_minecraft=1.21.10
jei_version=26.1.0.16