# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.5
neo_version=21.5.4-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.cobblegenhaters
mod_id=cobblegenhaters
mod_archive_name=Cobble-Gen-Haters

#Publishing
mod_name=Cobble Gen Haters
curseforge_id=305797
modrinth_id=fb5Ob6vt

# Version
version=2.1.0