modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/CobbleGenHaters/issues"
license="MIT"

[[mods]]
modId="cobblegenhaters"
version="${file.jarVersion}"
displayName="Cobble Gen Hater"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cobble-gen-haters"
credits="TheEmosewaPixel For the request"
authors="Mrbysco, TheEmosewaPixel"
description='''Want lava and water not to form cobble/stone? Then this is your mod.'''
[[dependencies.cobblegenhaters]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.cobblegenhaters]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"